spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: s3cr3t

liquigraph:
  url: jdbc:neo4j:${spring.neo4j.uri}
  user: ${spring.neo4j.authentication.username}
  password: ${spring.neo4j.authentication.password}
  enabled: true

app:
  omdb:
    apiKey: ${OMDB_API_KEY}